import React from 'react'
import type { Metadata } from "next";

import { ModeProvider } from "@/components/providers/mode";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ModeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ModeProvider>
            </body>
        </html>
    );
}

export default RootLayout